version: '3'
services:
 express:
   image: bryanenid/doorflash-api
   environment:    
   - DB_HOST mongodb+srv://BryanEnid:PptstCore15@cluster0-cia4k.mongodb.net
   - DB_NAME doorflash
   - DD_USER apptestbt@gmail.com
   - DD_PSWD PptstCore15
   ports: 
   - 3000:3000 
 nginx:
   image: nginx
   volumes:
   - ./proxy/verification:/usr/share/nginx/html/
   build: ./proxy
   ports: 
   - 80:80    
   - 443:443 
   depends_on:
   - express

     
# docker build -t bryanenid/doorflash-api . (DONT FORGET THE DOT)

#      TESTING
# docker run -it -p 3000:3000 bryanenid/doorflash-api (add 'sh' for the shell)
# docker ps -a
# docker pause 5e93e617f050

# docker login
# docker push bryanenid/doorflash-api

# docker run in foreground
# docker run -d --rm -p 3000:3000 bryanenid/doorflash-api
# docker run -d --rm -p 8000:80 -p 8443:443 --name pandorafms pandorafms/pandorafms:latest
# docker attach --name pandorafms
# docker stop 301aef99c1f3
#

# DOCKER COMPOSE!
# docker exec -it containerID bin/ash


###############################
# docker system prune -a

# Kill all running containers
# docker kill $(docker ps -a -q)

# Delete all stopped containers (including data-only containers)
# docker rm $(docker ps -a -q)

# Delete all 'untagged/dangling' (<none>) images
# docker rmi $(docker images -q -f dangling=true)

# Delete ALL images
# docker rmi $(docker images -q)